// Edge Function: publish
// Creates a GitHub repository with the generated extension files
// Uses the user's GitHub OAuth token from Supabase Auth

interface FileSpec {
  name: string;
  content: string;
}

interface PublishRequest {
  files: FileSpec[];
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    // Get GitHub token from Authorization header
    // The frontend sends the Supabase session token
    // We need to exchange it for the GitHub OAuth token
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "Unauthorized — no token provided" }),
        { status: 401, headers: { "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY");

    if (!supabaseUrl || !supabaseAnonKey) {
      return new Response(
        JSON.stringify({ error: "Supabase config missing" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    // Get user info from Supabase Auth
    const userRes = await fetch(`${supabaseUrl}/auth/v1/user`, {
      headers: {
        "Authorization": authHeader,
        "apikey": supabaseAnonKey,
      },
    });

    if (!userRes.ok) {
      return new Response(
        JSON.stringify({ error: "Invalid session" }),
        { status: 401, headers: { "Content-Type": "application/json" } }
      );
    }

    const { files } = await req.json() as PublishRequest;

    if (!files || !Array.isArray(files) || files.length === 0) {
      return new Response(
        JSON.stringify({ error: "Missing required field: files" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // For MVP: use a central GITHUB_TOKEN env var
    // In production, each user authenticates with their own GitHub via Supabase Auth
    const githubToken = Deno.env.get("GITHUB_TOKEN");
    if (!githubToken) {
      return new Response(
        JSON.stringify({ error: "GitHub token not configured" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    const repoUrl = await createRepo(githubToken, files);

    return new Response(
      JSON.stringify({ repoUrl }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
  } catch (err) {
    console.error("publish error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});

async function createRepo(githubToken: string, files: FileSpec[]): Promise<string> {
  const repoName = `makecode-ext-${Date.now()}`;

  // 1. Create the repository
  const createRes = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${githubToken}`,
      "Content-Type": "application/json",
      "User-Agent": "extension-builder",
    },
    body: JSON.stringify({
      name: repoName,
      description: "MakeCode Arcade extension generated by Extension Builder",
      private: false,
      auto_init: false,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json();
    throw new Error(`GitHub create repo failed: ${err.message}`);
  }

  const repo = await createRes.json();
  const owner = repo.owner.login;

  // 2. Commit each file
  for (const file of files) {
    const contentBase64 = btoa(file.content);

    const putRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/${file.name}`,
      {
        method: "PUT",
        headers: {
          "Authorization": `Bearer ${githubToken}`,
          "Content-Type": "application/json",
          "User-Agent": "extension-builder",
        },
        body: JSON.stringify({
          message: `Add ${file.name}`,
          content: contentBase64,
        }),
      }
    );

    if (!putRes.ok) {
      const err = await putRes.json();
      throw new Error(`GitHub commit failed for ${file.name}: ${err.message}`);
    }
  }

  return repo.html_url;
}
