-- Migration: 001_initial_schema
-- Creates the core tables for Extension Builder

-- Extensions generated by users
CREATE TABLE extensions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES auth.users NOT NULL,
  name        TEXT NOT NULL,
  prompt      TEXT NOT NULL,
  dsl         JSONB NOT NULL,
  files       JSONB NOT NULL,
  repo_url    TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

-- Stars / likes for the marketplace
CREATE TABLE extension_stars (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  extension_id UUID REFERENCES extensions(id) ON DELETE CASCADE NOT NULL,
  user_id      UUID REFERENCES auth.users NOT NULL,
  UNIQUE(extension_id, user_id)
);

-- Enable RLS
ALTER TABLE extensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE extension_stars ENABLE ROW LEVEL SECURITY;

-- RLS policies for extensions
CREATE POLICY "extensions_select_own"
  ON extensions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "extensions_insert_own"
  ON extensions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "extensions_delete_own"
  ON extensions FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- RLS policies for stars
CREATE POLICY "stars_select"
  ON extension_stars FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "stars_insert_own"
  ON extension_stars FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "stars_delete_own"
  ON extension_stars FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());
